<?php

/**
 * This is the model base class for the table "endpoint_capability".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EndpointCapability".
 *
 * Columns in table "endpoint_capability" available as properties of the model,
 * followed by relations of table "endpoint_capability" available as properties of the model.
 *
 * @property string $id
 * @property string $endpoint_id
 * @property string $capability_id
 *
 * @property Capability $capability
 * @property Endpoint $endpoint
 */
abstract class BaseEndpointCapability extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'endpoint_capability';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EndpointCapability|EndpointCapabilities', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('endpoint_id, capability_id', 'required'),
			array('endpoint_id', 'length', 'max'=>10),
			array('capability_id', 'length', 'max'=>1),
			array('id, endpoint_id, capability_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'capability' => array(self::BELONGS_TO, 'Capability', 'capability_id'),
			'endpoint' => array(self::BELONGS_TO, 'Endpoint', 'endpoint_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'endpoint_id' => null,
			'capability_id' => null,
			'capability' => null,
			'endpoint' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('endpoint_id', $this->endpoint_id);
		$criteria->compare('capability_id', $this->capability_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}